config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  # корень сайта
  root "events#index"

  resources :events do
    # вложенный ресурс комментов
    resources :comments, only: [:create, :destroy]

    # вложенный ресурс подписок
    resources :subscriptions, only: [:create, :destroy]

    # Вложенные в ресурс события ресурсы фотографий
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  # Поддерживаются только: show, edit, update
  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
# Модель событие
class Event < ApplicationRecord
  # Событие принадлежит юзеру
  belongs_to :user

  # У события много комментариев
  has_many :comments, dependent: :destroy

  # У события много подписок
  has_many :subscriptions, dependent: :destroy

  # У события много подписчиков (объекты User), через таблицу subscriptions,
  # по ключу user_id
  has_many :subscribers, through: :subscriptions, source: :user

  has_many :photos

  # Валидируем заголовок, он не может быть длиннее 255 букв
  validates :title, presence: true, length: {maximum: 255}
  # У события должны быть заполнены место и время
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
# Контроллер, управляющий событиями
class EventsController < ApplicationController

  # Встроенный в девайз фильтр — посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show, :index]

  before_action :set_event, only: [:show, :destroy, :edit, :update]

  # Проверка пин-кода перед отображением события
  before_action :password_guard!, only: [:show]

  after_action :verify_authorized, only: [:edit, :update, :destroy, :show]

  # GET /events
  def index
    @events = policy_scope(Event)
  end

  # GET /events/1
  def show
    authorize @event
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    # Болванка модели для формы добавления фотографии
    @new_photo = @event.photos.build(params[:photo])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  def create
    @event = current_user.events.build(event_params)

    if @event.save
      # Используем сообщение из файла локалей ru.yml
      # controllers -> events -> created
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private
    def password_guard!
    # Если у события нет пин-кода, то охранять нечего
    return true if @event.pincode.blank?
    # Пин-код не нужен автору события
    return true if signed_in? && current_user == @event.user

    # Если нам передали код и он верный, сохраняем его в куки этого юзера
    # Так юзеру не нужно будет вводить пин-код каждый раз
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    # Проверяем, верный ли в куках пин-код
    # Если нет — ругаемся и рендерим форму ввода пин-кода
    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end
      render 'password_form'
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  # Отредактируем параметры события
  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<%# Паршиал для отображения инфы об отдельном событии %>
<div class="col-sm-6 col-md-4 buffer-bottom">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l event.datetime, format: :short %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
        <%# Выводим всех пользователей, которые придут на событие, выводя их аватарки %>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# Паршиал для отображения формы создания нового события %>
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>События</h1>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Создание события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class="form-group">
    <%= label 'Пин-код', :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

<%= link_to 'На главную', events_path %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address,
                "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%= link_to 'Изменить', edit_event_path(@event),
                class: 'btn btn-primary buffer-x' %>

              <%= link_to 'Удалить', @event, method: :delete, data: {confirm: t('.are_you_sure')},
                class: 'btn btn-danger buffer-x' %>
            </div>
          <% end %>

        </div> <%# col-md-6 %>
        <div class="col-md-6">
          <div id="map" style="min-height: 300px" data-address='<%= @event.address %>'></div>
        </div>
      </div> <%# event-info-inner %>
    </div> <%# col-md-12 %>
  </div> <%# event-info %>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div> <%# event-photos-gallery %>
        <div class="event-photo-form buffer-both">
        <% if current_user %>
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        <% end %>
        </div> <%# event-photo-form %>
      </div> <%# event-photos %>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build} %>
        <div class="buffer-both">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div> <%# buffer-both %>
      </div> <%# event-comments %>
    </div> <%# col-md-8 %>

    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовет:</h4>
          <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>

      <div class="event-subscriptions">
        <h4>Пойдут:</h4>
        <div>
          <p>
          <%= render partial: 'subscriptions/subscription',
            collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% unless current_user_can_edit?(@event) %>
        <div class="event-subscription-form">
          <h4>Я пойду:</h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div> <%# row %>
</div> <%# event %>